//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 02:28:36 AM MSK 
//


package com.example.mass;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MassUnit.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MassUnit">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="pound"/>
 *     &lt;enumeration value="gr"/>
 *     &lt;enumeration value="kg"/>
 *     &lt;enumeration value="mg"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MassUnit")
@XmlEnum
public enum MassUnit {

    @XmlEnumValue("pound")
    POUND("pound"),
    @XmlEnumValue("gr")
    GR("gr"),
    @XmlEnumValue("kg")
    KG("kg"),
    @XmlEnumValue("mg")
    MG("mg");
    private final String value;

    MassUnit(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MassUnit fromValue(String v) {
        for (MassUnit c: MassUnit.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
