//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 02:28:36 AM MSK 
//


package com.example.candy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CandyType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CandyType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="caramel"/>
 *     &lt;enumeration value="toffee"/>
 *     &lt;enumeration value="chocolate"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CandyType")
@XmlEnum
public enum CandyType {

    @XmlEnumValue("caramel")
    CARAMEL("caramel"),
    @XmlEnumValue("toffee")
    TOFFEE("toffee"),
    @XmlEnumValue("chocolate")
    CHOCOLATE("chocolate");
    private final String value;

    CandyType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CandyType fromValue(String v) {
        for (CandyType c: CandyType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
