//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 02:28:36 AM MSK 
//


package com.example.candy;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.example.ingredients.ChocolateCandyIngredients;
import com.example.ingredients.NonChocolateCandyIngredients;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="calorific">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="4"/>
 *               &lt;fractionDigits value="1"/>
 *               &lt;minInclusive value="50"/>
 *               &lt;maxInclusive value="1000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="type" type="{http://www.example.com/Candy}CandyType"/>
 *         &lt;choice>
 *           &lt;element name="ingredientsChocolate" type="{http://www.example.com/Ingredients}ChocolateCandyIngredients"/>
 *           &lt;element name="ingredients" type="{http://www.example.com/Ingredients}NonChocolateCandyIngredients"/>
 *         &lt;/choice>
 *         &lt;element name="nutritionalValue" type="{http://www.example.com/Candy}NutritionalValue"/>
 *         &lt;element name="vendor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "calorific",
    "type",
    "ingredientsChocolate",
    "ingredients",
    "nutritionalValue",
    "vendor"
})
@XmlRootElement(name = "candy")
public class Candy {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected BigDecimal calorific;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected CandyType type;
    protected ChocolateCandyIngredients ingredientsChocolate;
    protected NonChocolateCandyIngredients ingredients;
    @XmlElement(required = true)
    protected NutritionalValue nutritionalValue;
    @XmlElement(required = true)
    protected String vendor;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the calorific property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCalorific() {
        return calorific;
    }

    /**
     * Sets the value of the calorific property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCalorific(BigDecimal value) {
        this.calorific = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link CandyType }
     *     
     */
    public CandyType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link CandyType }
     *     
     */
    public void setType(CandyType value) {
        this.type = value;
    }

    /**
     * Gets the value of the ingredientsChocolate property.
     * 
     * @return
     *     possible object is
     *     {@link ChocolateCandyIngredients }
     *     
     */
    public ChocolateCandyIngredients getIngredientsChocolate() {
        return ingredientsChocolate;
    }

    /**
     * Sets the value of the ingredientsChocolate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChocolateCandyIngredients }
     *     
     */
    public void setIngredientsChocolate(ChocolateCandyIngredients value) {
        this.ingredientsChocolate = value;
    }

    /**
     * Gets the value of the ingredients property.
     * 
     * @return
     *     possible object is
     *     {@link NonChocolateCandyIngredients }
     *     
     */
    public NonChocolateCandyIngredients getIngredients() {
        return ingredients;
    }

    /**
     * Sets the value of the ingredients property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonChocolateCandyIngredients }
     *     
     */
    public void setIngredients(NonChocolateCandyIngredients value) {
        this.ingredients = value;
    }

    /**
     * Gets the value of the nutritionalValue property.
     * 
     * @return
     *     possible object is
     *     {@link NutritionalValue }
     *     
     */
    public NutritionalValue getNutritionalValue() {
        return nutritionalValue;
    }

    /**
     * Sets the value of the nutritionalValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link NutritionalValue }
     *     
     */
    public void setNutritionalValue(NutritionalValue value) {
        this.nutritionalValue = value;
    }

    /**
     * Gets the value of the vendor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendor(String value) {
        this.vendor = value;
    }

}
