//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 02:28:36 AM MSK 
//


package com.example.ingredients;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BaseCandyIngredients complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseCandyIngredients">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="water" type="{http://www.example.com/Ingredients}ForcedMgMassValue"/>
 *         &lt;choice>
 *           &lt;element name="sugar" type="{http://www.example.com/Ingredients}ForcedMgMassValue"/>
 *           &lt;element name="fructose" type="{http://www.example.com/Ingredients}ForcedMgMassValue"/>
 *         &lt;/choice>
 *         &lt;element name="vanilin" type="{http://www.example.com/Ingredients}ForcedMgMassValue"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseCandyIngredients", propOrder = {
    "water",
    "sugar",
    "fructose",
    "vanilin"
})
@XmlSeeAlso({
    ChocolateCandyIngredients.class,
    NonChocolateCandyIngredients.class
})
public class BaseCandyIngredients {

    @XmlElement(required = true)
    protected ForcedMgMassValue water;
    protected ForcedMgMassValue sugar;
    protected ForcedMgMassValue fructose;
    @XmlElement(required = true)
    protected ForcedMgMassValue vanilin;

    /**
     * Gets the value of the water property.
     * 
     * @return
     *     possible object is
     *     {@link ForcedMgMassValue }
     *     
     */
    public ForcedMgMassValue getWater() {
        return water;
    }

    /**
     * Sets the value of the water property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForcedMgMassValue }
     *     
     */
    public void setWater(ForcedMgMassValue value) {
        this.water = value;
    }

    /**
     * Gets the value of the sugar property.
     * 
     * @return
     *     possible object is
     *     {@link ForcedMgMassValue }
     *     
     */
    public ForcedMgMassValue getSugar() {
        return sugar;
    }

    /**
     * Sets the value of the sugar property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForcedMgMassValue }
     *     
     */
    public void setSugar(ForcedMgMassValue value) {
        this.sugar = value;
    }

    /**
     * Gets the value of the fructose property.
     * 
     * @return
     *     possible object is
     *     {@link ForcedMgMassValue }
     *     
     */
    public ForcedMgMassValue getFructose() {
        return fructose;
    }

    /**
     * Sets the value of the fructose property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForcedMgMassValue }
     *     
     */
    public void setFructose(ForcedMgMassValue value) {
        this.fructose = value;
    }

    /**
     * Gets the value of the vanilin property.
     * 
     * @return
     *     possible object is
     *     {@link ForcedMgMassValue }
     *     
     */
    public ForcedMgMassValue getVanilin() {
        return vanilin;
    }

    /**
     * Sets the value of the vanilin property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForcedMgMassValue }
     *     
     */
    public void setVanilin(ForcedMgMassValue value) {
        this.vanilin = value;
    }

}
