//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 02:28:36 AM MSK 
//


package com.example.ingredients;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChocolateCandyIngredients complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChocolateCandyIngredients">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.com/Ingredients}BaseCandyIngredients">
 *       &lt;sequence>
 *         &lt;element name="chocolateKind" type="{http://www.example.com/Ingredients}ChocolateKind"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChocolateCandyIngredients", propOrder = {
    "chocolateKind"
})
public class ChocolateCandyIngredients
    extends BaseCandyIngredients
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ChocolateKind chocolateKind;

    /**
     * Gets the value of the chocolateKind property.
     * 
     * @return
     *     possible object is
     *     {@link ChocolateKind }
     *     
     */
    public ChocolateKind getChocolateKind() {
        return chocolateKind;
    }

    /**
     * Sets the value of the chocolateKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChocolateKind }
     *     
     */
    public void setChocolateKind(ChocolateKind value) {
        this.chocolateKind = value;
    }

}
